name: "Order Track"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6

      - name: "Setup Java"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "Build project"
        run: mvn clean install

      - name: "Login Docker"
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: "Build image"
        run: docker build -t devleochiarelli/ordertrack

      - name: "Publish Image"
        run: docker push devleochiarelli/ordertrack
  deploy:
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - name: "Pull image Docker Hub"
        run: docker pull devleochiarelli/ordertrack:latest

      - name: "Remove container"
        run: docker rm -f OrderTrack

      - name: "Run Docker container"
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} --name OrderTrack devleochiarelli/ordertrack:latest
